AN = input('Digite algo: ')
print('o tipo primitivo desse valor é {}.'.format(type(AN)))
print('Só tem espaços? ',AN.isspace())
print('É um número?',AN.isnumeric())
print('É alfabético?',AN.isalpha())
print('É alfanumérico?',AN.isalnum())
print('Está em maiúsculas?',AN.isupper())
print('Está em minúscula?',AN.islower())
print('Está capitalizada?', AN.istitle())
